### ISSUE TITLE
Omitted optional args cause error

### ISSUE THREAD

**Issue by positlabs** [rpgreen/apilogs#5]
I'm trying to get the logs from a single lambda function, but I'm having trouble. 

My aws-cli is configured with keys. Running `apilogs get /aws/lambda/cinemaMaster` spits out an error message complaining about missing optional args.

```
Traceback (most recent call last):
  File "/usr/local/bin/apilogs", line 11, in <module>
    sys.exit(main())
  File "/usr/local/lib/python2.7/site-packages/apilogs/bin.py", line 149, in main
    options.log_group_name = "API-Gateway-Execution-Logs_" + options.api_id + "/" + options.stage
TypeError: cannot concatenate 'str' and 'NoneType' objects
```

**Comment by positlabs** [comment]
Ah, it seems like apilogs was written mainly for API Gateway, which I'm not using. 

Maybe someone can point me in the right direction? I just want to stream logs from lambdas...

**Comment by rpgreen** [comment]
Look at awslogs repo instead

**Comment by positlabs** [comment]
Perfect, thank you!
