### ISSUE TITLE
Collect events from all associated lambdas

### ISSUE THREAD

**Issue by brnkrygs** [rpgreen/apilogs#7]
Hello! 👋 

I first wanted to say thanks for creating this tool. It promises to make our team's serverless development and support processes _significantly_ simpler. I appreciate the time you've spent here!

When we were kicking the tires yesterday, we noticed that when there are multiple lambdas associated to a gateway, apilogs was only reporting the events from the first lambda, instead of the whole collection.

I was able to fix the problem locally and expect to have PR on the way in the next day or so, but I wanted to get this recorded for your visibility.

**Comment by rpgreen** [comment]
Thanks for the PR! This looks like a regression that was introduced at some point.
